//
// Created by Joe Chrisman on 9/15/22.
//

#ifndef DEEPENING1_CONSTANTS_H
#define DEEPENING1_CONSTANTS_H

const int WINDOW_SIZE = 800;
const int SQUARE_SIZE = WINDOW_SIZE / 8;
const bool ENGINE_IS_WHITE = false;

const int DARK_SQUARE_COLOR = 0x222222;
const int LIGHT_SQUARE_COLOR = 0x777777;
const int CHECKING_SQUARE_COLOR = 0xff3131;
const int MOVE_OPTION_COLOR = 0x40e0d0;
const int PREVIOUS_MOVE_COLOR = 0x99ff99;

const int PIECE_SCORES[13] = {
    -100, // PLAYER_PAWN
    -400, // PLAYER_KNIGHT
    -500, // PLAYER_BISHOP
    -650, // PLAYER_ROOK
    -800, // PLAYER_QUEEN
    0, // PLAYER_KING
    100, // ENGINE_PAWN
    400, // ENGINE_KNIGHT
    500, // ENGINE_BISHOP
    650, // ENGINE_ROOK
    800, // ENGINE_QUEEN
    0, // ENGINE_KING
    0 // NONE
};



#endif //DEEPENING1_CONSTANTS_H
